[[redirects]]
  from = "/api/orders/*"
  to = "http://nova-alb-47947097.ap-south-1.elb.amazonaws.com/api/orders/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to = "http://nova-alb-47947097.ap-south-1.elb.amazonaws.com/api/:splat/"
  status = 200
  force = true
